version '3.3'
services:
 db:
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${db_name}
      MYSQL_USER: ${db_usernmae}
      MYSQL_PASSWORD: ${db_pass}
      MYSQL_ROOT_PASSWORD: ${root_pass}
    ports:
      - "3406:3406"
    volumes:
      - db-services:/var/lib/mysql
 sut:
   build: .
   dockerfile: Dockerfile.test
   links:
     - web
 web:
   build: .
   dockerfile: Dockerfile
   links:
     - redis
 redis:
   image: redis
